name: dose_gpt
description: "An offline, illness-first pediatric dosing tool for Ethiopian nurses and health officers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.4
  shared_preferences_web: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/data/illnesses.json
    - lib/data/drugs.json
    - lib/data/meta.json
    - assets/images/background/
    - assets/images/conditions/
